### ISSUE TITLE
Do not count shadow in dimensions

### ISSUE THREAD

**Issue by davidoskky** [srm985/axure-redline-tool#92]
Widgets with outer shadows are reported as larger than they actually are.
I would expect the plugin to display the actual dimensions of the widget and, in a separate property display the shadow dimensions.

To reproduce this in axure 9: Create an ellipse 100x100, add an outer shadow with parameters x=0, y=2, blur=3.
Clicking on the circle in axshare, the width and height displayed by the plugin are 106x106.

**Comment by srm985** [comment]
@davidoskky this is an awkward artifact of how Axure decided to create a circle or ellipse. For some reason instead of using HTML like every other shape, they instead decided to render an image of a circle... This is what gets uploaded to Axure Cloud. It should be noted that none of your attributes will show up in the tool if you use the ellipse. I have no idea why it is done like this, but the bug is documented here:
https://github.com/srm985/axure-redline-tool#bugs--drawbacks

To solve this, create a box instead and set the border radius to 50%. Then apply all of your attributes like normal.
